apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app.fullname" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "python-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}